spring:
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000

app:
  redis:
    enable: true

  cache:
    cacheType: REDIS
    cache-names:
      - bookByNameAndAuthor
      - booksByCategory
      - bookById
    caches:
      bookByNameAndAuthor:
        expiry: 1m
      booksByCategory:
        expiry: 1m
      bookById:
        expiry: 1m
